/// <reference types="vite/client" />

// Neutralino global variables
declare const NL_ARGS: string[];
declare const NL_PORT: number;
declare const NL_TOKEN: string;
declare const NL_CWD: string;
declare const NL_PATH: string;
declare const NL_VERSION: string;
declare const NL_CVERSION: string;
declare const NL_APPID: string;
declare const NL_APPVERSION: string;
declare const NL_MODE: string;
declare const NL_OS: string;
declare const NL_ARCH: string;
declare const NL_COMMIT: string;
declare const NL_PID: number;
declare const NL_RESMODE: string;
declare const NL_EXTENABLED: boolean;
declare const NL_CMETHOD: string;
